### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by f-mio** [f-mio/furima-32852#9]
項目|内容
--|--
自身のフリマアプリのURL | https://furima-32852.herokuapp.com/
Basic認証のIDとパスワード |  user : admin, pass : 1234567
出品者用のメールアドレスとパスワード | test_user@test.com, pass : aaa111
購入者用のメールアドレスとパスワード | test_user2@test.com, pass : aaa111
購入用カードの番号・期限・セキュリティコード | 4242424242424242, 10/22, 123

**Comment by chisesakai** [comment]
フリマアプリ挙動確認依頼ありがとうございます！
#### フリマアプリ完了報告フォームへご提出お願いいたします。

只今、コードレビュー依頼フォームにて送信いただいておりますため、
カリキュラムをご確認いただき、**フリマアプリ完了報告フォームより再度ご提出をお願い致します。**

もしご不明な点がございましたら担当ライフコーチにご確認いただけますと幸いです。
お手数をおかけいたしますが、よろしくお願い致します！

**Comment by f-mio** [comment]
間違い大変申し訳ありませんでした。
正しいフォームで再度依頼させていただきます。

**Comment by naru6117** [comment]
@f-mio さん、ご提出ありがとうございます！
挙動確認させて頂いたところ、以下の不備が見受けられましたので修正をお願いします！

[修正依頼箇所]

- [ ] **商品購入ページでは、一覧や詳細ページで選択した商品の情報が出力されるようにしましょう！**
現状、表示されている価格に差異が生じています。
![Furima-32852](https://user-images.githubusercontent.com/49669977/109441974-32b12100-7a7a-11eb-962d-c0504e796da6.png)


修正ができましたら、以下の最終課題完了報告フォームを再度提出お願いします！
※新しいissueを作っていただく必要はありません
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by f-mio** [comment]
ご確認いただきましてありがとうございます。
購入者負担の場合に運送代金を暫定で1000円値上げする意図で表示を変えておりました。ただ、よく確認すると金額には送料込みの記載があります。ですので、この内容自体が不適切と考え、記述を削除いたしました。
お手数おかけし申し訳ありませんが、今一度ご確認いただきますようお願い申し上げます。

**Comment by naru6117** [comment]
@f-mio さん、ご提出ありがとうございます！
そうだったのですね。
カリキュラムのままに実装するだけではなく、ご自身で考え実装されており、素晴らしいですね！
再度挙動確認させて頂いたところ、以下の不備が見受けられましたので修正をお願いします。

[修正依頼箇所]

- [ ] **issueに記載されたHerokuのURLにアクセスし、同じくissueに記載されたIDとパスワードを入力すると、最終課題アプリ（FURIMA）が表示されるようにしましょう！**
挙動確認中に下記のエラーになってしまい、その後再度アクセスし直してもエラー画面になってしまう状況です。
デプロイがうまくいっていない可能性もございますので、ご確認をお願いいたします。
![スクリーンショット 2021-03-01 18 56 20](https://user-images.githubusercontent.com/49669977/109481477-2354c680-7ac0-11eb-960d-a831a7f52087.png)


修正ができましたら、以下の最終課題完了報告フォームを再度提出お願いします！
※新しいissueを作っていただく必要はありません
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by f-mio** [comment]
ご確認ありがとうございます。

ログを確認しましたところ、下記の3点で
・ビューitem.html.erb121行目　<%= render partial: "items/item", collection: @items %>
・item_controller　indexアクション内9行目　  @items = Item.find_by_sql(query)
・item_controller　createアクション内21行目      render :new
でstatus 500が生じておりました。
また、DB再起動のためにheroku run rails db:migrateコマンドを行なったところ、
User XXX has exceeded the 'max_questions' resource.
と表示されまして、不具合の原因としては、1時間にヘロクの応答回数3600を超える処理をしてしまったことが原因と思われます。
恐れ入りますが、直前に行なった処理についてご教示いただけないでしょうか？

【私の方での追跡調査】
コードの不備で意図しない繰り返し処理が行われた可能性を考え検証しました。
そこで、herokuデータベースの再起動を行い、
% heroku log --tail --app furima-32852
下記の負荷がかかると思われる処理を実行しましたが、エラー表示が現れませんでした。
　・root_pathのページで再読み込みの繰り返し
　・ログイン情報を続けて失敗する。　(3回程度)
　・商品出品を続けて失敗する。　(2回程度)

**Comment by takumi0530** [comment]
@f-mioさん、再度ご提出ありがとうございます。
ご返信いただいている件に関しまして、本日該当のレビューをした者が休みをいただいており、詳細な情報がお伝えできません。解決にお力添えができず、申し訳ございません。

こちらに関しまして疑問点がある場合は、テックコネクトにてご質問いただいても構いませんでしょうか？
また、先日お伝えしたものと同じ現象がおきましたので、状況と共にお伝えいたします。

**【修正箇所】**

- [ ] **issueに記載されたHerokuのURLにアクセスし、同じくissueに記載されたIDとパスワードを入力すると、最終課題アプリ（FURIMA）が表示されるようにしましょう！**

挙動確認中に起きてしまいました。当時の状況は以下の通りになります。

```
・2回目の出品中、情報を埋めて出品を押した際にエラーページへ遷移してしまいました。
・戻るボタンや更新をしても治らなかったため、1度ページを閉じ、新しいタブで開き直しました。
・開き直したものは最初からエラーページを表示してしまいました。
```

修正ができましたら、以下の最終課題完了報告フォームを再度提出お願いします！
※新しいissueを作っていただく必要はありません
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by f-mio** [comment]
メンター様と話いたしましたが、エラーの発生原因を掴むことができませんでした。
そのため、レビュー依頼を受け取っていただいた後に、下記のコメントをご確認ください。

・後日ライフコーチさんと情報共有したい、とのこと。
・もしWe're sorry出ましたら時間を置いて再度確認いただき、また、どのような操作で発生したかをコメントで教えていただければと思います。

対応していただいたメンターさんの名前は私の方の担当ライフコーチに連絡済みですので、お手数ですがご確認お願いいたします。

また、もし解決しないようでしたら、herokuのデプロイを0からやり直してみたいのですが、いかがでしょう？
理由としましては、2/21に作成したマイグレーションファイルをカラム名変更をするために削除したことがあるためです。
この間に新しくマイグレーションファイルを作成したのですが、前のものが残って動作に影響を与えた可能性があると考えたからです。

**Comment by takumi0530** [comment]
@f-mio さん、再度ご提出ありがとうございます！！お待たせしてしまい、申し訳ございません。
先ほど問題なく正常に動作することが確認できました！　LGTMです✨　
おめでとうございます！！

**【補足】**
必須条件はクリアされておりますが、企業にこちらを提出する際に同じような現象が起こってしまうと不利になりかねませんので、**出品されている商品のデータを一旦削除してみる**などの実装を続けると良いかと思います。

**※確認したのは必須機能のみです。追加実装した機能については確認しておりません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるか、再度ご自身でご確認をお願い致します。**
![最終課題終了_おめでとう画像2](https://user-images.githubusercontent.com/76197191/109742752-f664f880-7c12-11eb-8c9d-3eef161c7668.png)
